### PR TITLE
do stuff

### PR DESCRIPTION
**Pull request by AleksanderBodurri**

### CODE REVIEW

**Comment by HassanA01** [comment]
looks good to me!

**Comment by hpnrep6** [comment]
LGTM

**Comment by navn-r** [comment]
Rewrite it pls 💩

**Comment by hpnrep6** [comment]
> Rewrite it pls 💩
> 
> LETS GOO [ LETS GOO ](https://camo.githubusercontent.com/7ce5e6c13bd20c192f5513127ea559a4a87feb1b3a4d6bb3f12c6d4e334959b9/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e33413365477836635456704d6e64734e6d67304e44686f6232646d636a64744e3270304e5739345a57357763327830625870745a695a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f736c317a665750716c6f7a4f6771757a75452f67697068792e676966) [ ](https://camo.githubusercontent.com/7ce5e6c13bd20c192f5513127ea559a4a87feb1b3a4d6bb3f12c6d4e334959b9/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e33413365477836635456704d6e64734e6d67304e44686f6232646d636a64744e3270304e5739345a57357763327830625870745a695a6c634431324d563970626e526c636d35686246396e61575a66596e6c666157516d593351395a772f736c317a665750716c6f7a4f6771757a75452f67697068792e676966)

uwu

**Comment by navn-r** [comment]
NOT COOL ENOUGH 👎

**Pull request closed without merging**
