### PR TITLE
Update ngx-turnstile to support Angular 16.

### PR DESCRIPTION
**Pull request by natereprogle**
This pull request is to update ngx-turnstile to support the latest Angular 16. Due to changes in Angular's compiler, this also adjusts the polyfill settings within the `tsconfig.app.json` to fix testing errors that came up as a result of this upgrade, and removes some unnecessary files as a result of these edits.

### CODE REVIEW

**Comment by natereprogle** [comment]
Hey there! Any update on this pull?

**Comment by AleksanderBodurri** [comment]
@natereprogle hey Nate, thanks for the PR 🙏  Could you rebase this onto `main` ?

**Comment by natereprogle** [comment]
Hey @AleksanderBodurri, I think I got it! Let me know if this works, thanks!

**Review by AleksanderBodurri — APPROVED** [review]

**Comment by AleksanderBodurri** [comment]
merged, thanks again 🙏

**Comment by natereprogle** [comment]
Thank you! This is a great project, I appreciate you creating your team creating it for the community!

**Pull request merged**
